version: "3.1"
services:
    dplr:
        build:
            context: ./docker/images/dplr
            args:
                PHP_VERSION: ${PHP_VERSION:-7.4}
        working_dir: /var/www/dplr
        volumes:
            - ./:/var/www/dplr
        environment:
            - HOME=/var/www/dplr
            - COMPOSER_HOME=~/.composer
    remote_1:
        build: docker/images/remote
    remote_2:
        build: docker/images/remote
    remote_3:
        build: docker/images/remote
